<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="OpenAPIs\swagger.json" />
	</ItemGroup>

	<ItemGroup>
		<!-- Code generation tools -->
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="NSwag.ApiDescription.Client" Version="14.7.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="NSwag.MSBuild" Version="14.7.1" />

		<!-- Configuration -->
		<OpenApiReference Include="OpenAPIs\swagger.json" SourceUrl="https://localhost:7044/swagger/v1/swagger.json" CodeGenerator="NSwagCSharp">
			<Namespace>LexisNexis.ProductCatalog.Clients</Namespace>
			<ClassName>ProductCatalogApiClient</ClassName>
		</OpenApiReference>
	</ItemGroup>

</Project>
